mavenagi-apps/chat

- INSTALL.md
- app/[orgFriendlyId]/[id]/page.tsx
- app/api/create/route.ts
- app/api/utils.ts
- app/constants/authentication.ts
- app/demo/[orgFriendlyId]/[agentFriendlyId]/actions.ts
- app/demo/[orgFriendlyId]/[agentFriendlyId]/page.tsx
- lib/useIframeMessaging.ts
- package.json
- packages/components/chat/use-chat.tsx
- packages/widget/src/chat/hooks/useIframeCommunication.ts
- packages/widget/src/chat/index.tsx
- pnpm-lock.yaml
- settings.d.ts
This is up and running right now at https://chat-develop.onmaven.app/demo/monarch/godzilla
The demo site generates a signed and encrypted userData payload with faker data on every page load.
This PR adds support for securely handling authenticated user data in the Maven chat system. It enables customers to pass encrypted and signed user data (like email, phone, etc.) which is then securely decrypted and verified before being used to create authenticated Maven users.
Key Features:
- Secure JWT-based encryption and signature verification for user data
- Support for authenticated users with email/phone identifiers
- Maintains user context across chat sessions
- Graceful fallback to anonymous users on missing or invalid data
- Demo implementation showing how customers can implement the …
> Add Secure User Authentication via Encrypted JWT

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
this will run `npx lint-staged` on pre-commit which will in turn run prettier on the code base
> [APP-627] Add husky and lint-staged

- app/api/create/route.ts
This PR https://github.com/mavenagi/highlander/pull/6085/files in highlander added action filtering and now `forms` are not supported by default... `Forms` need to be added to the list of capabilities so the correct actions are included
> CX-1449: add forms to the list of capabilities

- INSTALL.md
- next.config.mjs
- packages/widget/vite.config.base.ts
Updating domain settings and docs to point to new `chat.onmaven.app` domain
> chore!: migrate to chat.onmaven.app

- app/api/create/route.ts
- messages/en.json
- messages/es.json
- messages/fr.json
- messages/it.json
- package.json
- packages/components/chat/BailoutFormDisplay.tsx
- packages/components/chat/ChatMessage.tsx
- packages/components/chat/use-chat.tsx
- pnpm-lock.yaml
- Added Highcharts capability to the chat response configuration
- Implemented chart rendering support in ChatMessage component
- Added error handling and translations for chart rendering failures
- Added type definitions for chart responses
- Added `MavenAGI.Capability.ChartsHighchartsTs` to conversation initialization
- Created new `MessageCharts` component to handle chart rendering
- Added error boundary with translated error messages for failed chart renders
- Extended stream response handling to process chart events
- Added translations for chart error messages in all supported languages (en, es, fr, it)
> feat: Add highchart support

- app/api/zendesk/index.d.ts
- app/api/zendesk/messages/route.ts
- app/api/zendesk/webhook/route.ts
- lib/useHandoff.ts
- package.json
- packages/components/chat/ChatMessage.tsx
- pnpm-lock.yaml
- settings.d.ts
- types/index.ts
- types/zendesk/index.ts
This PR implements several improvements to enhance the stability and reliability of our pub/sub and stream functionality, particularly focusing on the Zendesk integration.
- Added webhook ID support in message payload for better traceability
- Implemented webhook configuration error handling
- Added the foundations for webhook secret validation for improved security
- Implemented keep-alive interval to maintain stable connections
- Added reconnection logic with configurable interval
- Enhanced connection status handling for more reliable communication
- Added new type definitions:
- `HandoffChatMessage` for consistent message handling
- `ZendeskMessagePayload` for type-safe webhook payloads
- Added `@vercel/functions` package for improved serverless function stability
- Updated …
> feat: zendesk chat stream stability

- app/api/front/client.ts
- types/front/index.ts
Utilization of this code is coming up... Just trying to keep PRs small and readable
> APP-676: Add FrontCoreClient and adjust Front types

- app/[orgFriendlyId]/[id]/page.tsx
- app/actions.ts
- packages/components/chat/ChatMessage.tsx
- packages/components/chat/ChatMessages.tsx
- packages/components/chat/FeedbackForm.tsx
- packages/components/chat/use-chat.tsx
We could add to the context to avoid the prop drilling but this is working for now.
> [APP-593] Add userid for feedback

- app/[orgFriendlyId]/[id]/page.tsx
- app/api/front/client.ts
- app/api/front/conversations/route.ts
- app/api/front/route.ts
- app/api/front/utils.ts
- app/api/server/lib/maven.ts
- app/api/server/utils.ts
- app/api/zendesk/conversations/passControl/route.ts
- app/api/zendesk/conversations/route.ts
- app/api/zendesk/messages/route.ts
- app/api/zendesk/utils.ts
- lib/jsonFetch.ts
- lib/useHandoff.ts
- packages/components/chat/Chat.tsx
- packages/components/chat/ChatMessage.tsx
- packages/components/chat/ChatMessages.tsx
- settings.d.ts
- types/index.ts
- types/zendesk/index.ts
> APP-676: Sync initial chat messages to front during agent handoff

- app/actions.ts
- packages/components/chat/WelcomeChatMessage.tsx
- settings.d.ts
Currently available to test on https://chat-develop.onmaven.app/demo/monarch/godzilla
This PR adds support for customizable welcome messages with markdown and multi-language support in the chat interface.
- Added `welcomeMessage` field to app settings
- Enhanced `WelcomeChatMessage` component to handle localized and non-localized welcome messages
- Welcome messages can be provided as a JSON object with locale keys (e.g., en, es, fr, it)
- Falls back to English (en) if translation not available for current locale
- Preserves existing default welcome message as fallback if no custom message is set
- Welcome messages are stored as plain strings or JSON strings with locale keys
- Uses `next-intl` for locale detection
- Maintains markdown support through ReactMarkdown component
- Handles JSON …
> [feat] Customizable welcome message

- app/[orgFriendlyId]/[id]/page.tsx
- app/api/front/conversations/passControl/route.ts
- app/api/front/conversations/route.ts
- app/api/front/messages/route.ts
- app/api/front/utils.ts
- app/api/front/webhook/[orgFriendlyId]/[agentFriendlyId]/route.ts
- lib/useHandoff.ts
- packages/components/chat/Chat.tsx
- packages/components/chat/ChatMessage.tsx
- packages/components/chat/ChatMessages.tsx
- types/front/index.ts
- types/index.ts
> APP-676: Receive messages from Front agent

- __tests__/app/api/zendesk/conversations/route.test.ts
- __tests__/app/api/zendesk/messages/route.test.ts
- __tests__/packages/components/chat/BailoutFormDisplay.test.tsx
- __tests__/packages/components/chat/use-chat.test.tsx
- app/api/front/route.ts
- app/api/front/utils.ts
- app/api/zendesk/messages/route.ts
- app/api/zendesk/webhook/route.ts
- messages/en.json
- messages/es.json
- messages/fr.json
- messages/it.json
- packages/components/chat/ChatCard.tsx
- packages/components/chat/ChatHeader.tsx
- packages/components/chat/ChatInput.tsx
Non-functional portion of https://github.com/mavenagi-apps/chat/pull/45
> chore: update tests and translation objects

- app/api/create/route.ts
- app/api/zendesk/conversations/route.ts
Backend changes in #45 
Updates the /api/zendesk/ endpoint to accept `email` string
Updates the /api/zendesk/ endpoint to create anonymous users with the Zendesk SDK
> feat: update zendesk handoff api to handle anonymous users

- middleware.ts
Quick log to address issue in discord
> feat: add conditional log to csp middleware

- INSTALL.md
Just fleshing out the installation instructions to fix a couple errors I encountered locally and adding commands to generate secrets
> docs: add more details to installation readme

- __tests__/app/api/create/route.test.ts
- __tests__/packages/components/chat/use-chat.test.tsx
- app/api/create/route.ts
- app/api/salesforce/conversations/route.ts
- app/api/salesforce/messages/route.ts
- packages/components/chat/use-chat.tsx
This PR adds support for passing arbitrary user information to the chat system through unsigned data. This information is injected as a system message at the start of conversations, allowing the AI to have context about the user without requiring signed/verified data.
- Added support for `unsignedUserData` in the chat widget and API
- System message is automatically generated with user information at conversation initialization
- Maintains backwards compatibility with existing signed user data flow
- Added comprehensive error handling and logging
- Modified conversation initialization to include user data as a system message
- Added `unsignedUserData` parameter to relevant interfaces and API endpoints
- Enhanced error logging with `console.error` for better debugging
- Added type safety …
> feat: provide unsignedUserData to chat as an external system message

- packages/components/chat/ChatMessage.tsx
> chore(app): RTL support for chat bubble

- messages/es.json
- messages/fr.json
- messages/it.json
Updates translation content to match `en.json` and remove hardcoded values.
> fix: remove hardcoded urls

- app/api/front/messages/route.ts
The front live handoff keeps ending the chat after a short period of time. Port over the keep-alive logic from ZD
> feat: use keep-alive for front agent handoff

- app/api/front/client.ts
- app/api/front/conversations/route.ts
- lib/jsonFetch.ts
- types/front/index.ts
Note the custom `data` attribute
> APP-245:  update Front contact with custom data provided in signedUserInfo

- __tests__/app/api/salesforce/conversations/passControl/route.test.ts
- __tests__/app/api/salesforce/conversations/route.test.ts
- app/api/salesforce/conversations/passControl/route.ts
- app/api/salesforce/conversations/route.ts
- app/api/zendesk/conversations/route.ts
- app/demo/[organizationId]/[agentId]/Widget.tsx
- revert changes to demo components to align with unit tests
- remove noise from test results
- remove console log statements
- stub expected console error statements
> chore: revert demo changes to align with tests

- __tests__/packages/components/chat/Chat.test.tsx
- __tests__/packages/components/chat/ChatInput.test.tsx
- app/[organizationId]/[agentId]/page.tsx
- app/actions.ts
- packages/components/chat/Chat.tsx
- packages/components/chat/ChatInput.tsx
- settings.d.ts
> chore(platform): hide attach icon in handoff mode

- __tests__/app/actions.test.ts
- __tests__/lib/settings.test.ts
- __tests__/middleware.test.ts
- app/actions.ts
- app/api/server/utils.ts
- lib/settings.ts
- middleware.ts
- settings.d.ts
> chore: remove logs

- __tests__/lib/handoff/SalesforceStrategy.test.ts
- lib/handoff/SalesforceStrategy.ts
Changes:
- Added type guard for agent name bearing events (ChatMessage and ChatTransferred)
- Updated agent name extraction to handle both ChatMessage and ChatTransferred events
Impact:
- Agent names now extracted from both ChatMessage and ChatTransferred events
- Type safety improvements through TypeScript type guard
Testing:
- Added test coverage for ChatMessage agent name handling
- Added test coverage for non-agent events
- Updated existing test expectations for agent name presence
> feat: improve Salesforce chat event agent name handling

- app/api/salesforce/utils.ts
per: https://help.salesforce.com/s/articleView?id=000386079&type=1
> fix: update affinity headers in sf session id request

- packages/widget/src/chat/hooks/useIframeCommunication.ts
- packages/widget/src/chat/index.tsx
Changes
- Added constants for positioning, spacing, and style values in `useIframeCommunication.ts
`- Added support for configurable iframe positioning through `horizontalPosition` and `verticalPosition` properties
- Updated iframe style generation to dynamically position the widget in any of the four corners
- Updated transform origin to match the selected position for proper scaling animation
> fix: position iframe by widget properties

- INSTALL.md
- __tests__/packages/components/chat/Chat.test.tsx
- packages/components/chat/Chat.tsx
Reverts mavenagi-apps/chat#147
need to fix the font colors for existing customers first
> Revert "feat: change default brand font color to black"

- __tests__/app/api/salesforce/utils.test.ts
- __tests__/lib/handoff/ZendeskStrategy.test.ts
- settings.d.ts
- src/lib/handoff/FrontStrategy.ts
- src/lib/handoff/HandoffStrategyFactory.ts
- src/lib/handoff/SalesforceStrategy.ts
- src/lib/handoff/ZendeskStrategy.ts
- src/lib/useHandoff.ts
- src/types/zendesk/index.ts
- Added agent availability check for Zendesk handoff
- Extended ZendeskHandoffConfiguration with availability check settings
- Implemented ZendeskServerStrategy.fetchHandoffAvailability method
- Added ZendeskAgentAvailabilityResponse type
- Updated tests for ZendeskStrategy and ZendeskServerStrategy
- Fixed unresolved promises in Salesforce utils tests
> feat: check zendesk  live agent availability
