mavenagi-apps/chat

packages/components/chat/WelcomeChatMessage.tsx, settings.d.ts
Updating `popularQuestions` appSettings property from `string` ➡️ `string[]`. This PR makes the property backwards compatible until we migrate all users.
=> fix: make popular questions backwards compatible

packages/components/chat/use-chat.tsx
Chart messages erroneously included an `action` property that caused a blank action form to be displayed.
=> fix: Remove 'action' key from chart messages

app/api/server/lib/redis.ts, app/api/zendesk/messages/route.ts, app/api/zendesk/webhook/route.ts
Context: Our Zendesk webhook was subscribing to events before the redis client connected.
This PR moves the "wait for connection" call to the redis dependency rather than the webhook route.
=> fix: await redis init before pub/sub

app/api/server/lib/redis.ts, app/api/zendesk/messages/route.ts, app/api/zendesk/webhook/route.ts
Update to resolve the error `ERR Can't execute 'publish': only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context`
According to this [SO answer](https://stackoverflow.com/a/51585392), a client can only subscribe or publish but not both at the same time
=> fix: create separate publish and subscribe clients

app/api/front/client.ts, app/api/front/utils.ts, types/front/index.ts
Add client methods that will be used to import messages for a conversation that was not escalated to an agent... coming up in a follow up PR
=> APP-749: add front client code to sync conversations that were not escalated to an agent

__tests__/lib/handoff/FrontStrategy.test.ts, __tests__/lib/handoff/HandoffStrategyFactory.test.ts, __tests__/lib/handoff/ZendeskStrategy.test.ts, __tests__/lib/handoff/strategies.test.ts, __tests__/lib/handoff/test-helpers.ts, __tests__/lib/useHandoff.test.ts, lib/handoff/FrontStrategy.ts, lib/handoff/HandoffStrategy.ts, lib/handoff/HandoffStrategyFactory.ts, lib/handoff/ZendeskStrategy.ts, lib/useHandoff.ts
Here's a PR description for the chat handoff refactoring:
This PR introduces a refactor of the chat handoff system to improve maintainability and extensibility.
- Created a new `HandoffStrategy` interface to standardize handoff implementations
- Added dedicated strategy classes for Zendesk and Front integrations
- Centralized message formatting and event handling logic
None. This refactoring maintains backward compatibility while providing a more robust foundation for future handoff integrations.
- Sets up salesforce handoff strategies
- Addresses technical debt in chat handoff system
- Improves maintainability for future integrations
=> Refactor chat handoff

__tests__/app/[orgFriendlyId]/[id]/page.test.tsx, __tests__/app/demo/[orgFriendlyId]/[agentFriendlyId]/page.test.tsx, app/[orgFriendlyId]/[id]/__tests__/page.test.tsx, app/[orgFriendlyId]/[id]/page.tsx, app/demo/[orgFriendlyId]/[agentFriendlyId]/page.tsx, app/providers/AuthProvider.tsx, app/providers/CustomDataProvider.tsx, lib/useIframeMessaging.ts, packages/widget/src/chat/hooks/useIframeCommunication.ts, packages/widget/src/chat/index.tsx
This PR adds support for passing unsigned user data and custom data through the iframe messaging system, enabling better user identification and customization options in the chat widget.
- Added `UNSIGNED_USER_DATA` and `CUSTOM_DATA` message types for iframe communication
- These complement the existing `SIGNED_USER_DATA` type for a more complete user data handling system
1. Widget load now accepts:
- `unsignedUserData`: For basic user info (name, email, etc.)
- `customData`: For arbitrary custom properties
2. Data is passed through the iframe messaging system
3. Data is made available via context providers in the chat application
- Added `CustomDataProvider` to manage custom data throughout the app
- Updated `AuthProvider` to handle both signed and unsigned user data
- Both providers …
=> feat: add properties to widget-to-iframe communication

app/api/server/utils.ts
To support testing against different maven branches (main, develop, local), there needs to be multiple instances of the same channel installed... To direct messages to the right instance, the configuration needs to be able to define the channel name.
This just checks to see if the value is already set... instead of always replacing
=> fix: don't override front configuration channel name

app/api/front/route.ts
`VERCEL_PROJECT_PRODUCTION_URL` is the correct env. var to use to get the production URL
=> fix: update vercel prod url

lib/useHandoff.ts, lib/useScrollToBottom.ts, packages/components/chat/ChatMessages.tsx
1. Updated the `useScrollToBottom` observer properties to only monitor for new elements in the chat messages list. Previously, it was traversing the sub tree and detecting any html changes, including markdown->html in message bodies.
2. Removed the timer that manages the typing indicator. We don't have proper requirements for it yet and it keeps re-rendering the component.
3. Removed an unused dep in `ChatMessages`
=> fix: scroll to bottom triggers on new message only

__tests__/app/api/salesforce/conversations/passControl/route.test.ts, __tests__/app/api/salesforce/conversations/route.test.ts, __tests__/app/api/salesforce/messages/route.test.ts, __tests__/packages/components/chat/use-chat.test.tsx, app/api/front/webhook/[organizationId]/[agentId]/route.ts, app/api/salesforce/conversations/passControl/route.ts, app/api/salesforce/conversations/route.ts, app/api/salesforce/messages/route.ts, app/api/salesforce/utils.ts, app/api/server/utils.ts, app/constants/authentication.ts
This PR adds API endpoints to support handoff functionality to Salesforce Live Agent chat, enabling transition from Maven bot to live Salesforce agents.
- `/api/salesforce/conversations` - Handles chat session initialization and setup
- `/api/salesforce/conversations/passControl` - Manages chat session termination
- `/api/salesforce/messages` - Handles bi-directional message streaming between Maven and Salesforce
- **Chat Session Management**: Full lifecycle support for Salesforce chat sessions including initialization, message handling, and termination
- **Real-time Message Streaming**: Server-sent events implementation for real-time message delivery
- **Transcript History**: Automatic transfer of Maven chat history to Salesforce agents
- **Authentication**: JWT-based authentication for …
=> App 829 partial sf api

__tests__/app/demo/[organizationId]/[agentId]/page.test.tsx, app/demo/[organizationId]/[agentId]/page.tsx
This PR adds support for passing custom data to the chat widget through URL search parameters. Users can now include a `customData` parameter in the demo page URL to initialize the widget with custom key-value pairs.
- Added support for `customData` URL parameter in the demo page
- Implemented JSON parsing of the `customData` parameter with error handling
- Merged parsed custom data with default values (preserving existing `buttonId`)
- Added comprehensive tests for custom data handling scenarios
Users can now pass custom data through the URL like:
```url
/demo/org/agent?customData={"key":"value","numberKey":123}
```
Added tests for:
- Valid custom data parsing and inclusion
- Invalid JSON handling
- Default behavior when no custom data is provided
- Parameter validation
- Invalid JSON in …
=> feat: allow url search params to populate customdata

__tests__/app/demo/[organizationId]/[agentId]/page.test.tsx, app/demo/[organizationId]/[agentId]/page.tsx
- removed a placeholder id on the demo page (interfered with handoff params)
- updated demo page tests
=> chore: remove placeholder button id in demo

__tests__/app/api/salesforce/conversations/route.test.ts, app/api/salesforce/conversations/route.ts, app/api/salesforce/messages/route.ts, app/api/salesforce/utils.ts
Adds conditional transcript delivery based on Salesforce chat session initialization status.
- Added check for ChatRequestSuccess message before sending initial messages
- Moved fetchChatMessages function to utils for reusability
- Added tests for ChatRequestSuccess message handling
- Updated existing conversation tests
- All tests passing
=> feat: conditionally send transcript in sf chat handoff

app/api/front/client.ts, lib/jsonFetch.ts
I already have this in the front repo to handle message syncing failures for ticket creation and its working well... I need to bring this over here too.
The implements rate-limiting and retries following Front's guidelines
=> Add front rate-limiting

app/api/front/client.ts, app/api/front/utils.ts
Refactor retry logic for FrontApplicationClient to reuse the shared rate-limiting logic from the FrontCoreClient
=> APP-245: refactor retry logic for FrontApplicationClient

__tests__/app/api/create/route.test.ts, app/api/create/route.ts
The customFields object provided by scratchpay is turning into `[object Object]` instead of properly serialized output.
=> APP-245: handle stringifying objects and arrays

middleware.ts
Envars outside of the middleware method resolve as undefined
=> fix: re-scope envar in middleware

__tests__/app/demo/[organizationId]/[agentId]/Widget.test.tsx, __tests__/app/demo/[organizationId]/[agentId]/page.test.tsx, app/demo/[organizationId]/[agentId]/Widget.tsx, app/demo/[organizationId]/[agentId]/page.tsx
A number of demo's want Maven chat to know what today's date is. Until the platform's prompt handles this universally, we're using `unsignedUserData` to pass to to the demo page widget so the chat is primed with today's date alongside the mock user data.
=> feat: [chat][demo page] Prime chat with today's date

__tests__/lib/handoff/SalesforceStrategy.test.ts, __tests__/packages/components/chat/ChatMessage.test.tsx, lib/handoff/SalesforceStrategy.ts, messages/en.json, messages/es.json, messages/fr.json, messages/it.json, packages/components/chat/ChatMessage.tsx, types/salesforce/index.ts
Adds support for rendering event messages when a Salesforce chat request fails, particularly handling the case when no agents are available.
- Added `SalesforceChatRequestFail` and `SalesforceChatRequestFailUnavailable` types
- Updated `SalesforceStrategy.handleChatEvent()` to handle unavailable agent scenarios
- Added translations for unavailable agent messages
- Added test coverage for chat request fail scenarios in both `SalesforceStrategy` and `ChatMessage` components
- Added unit tests for rendering chat request fail messages
- Added tests for both available and unavailable agent scenarios
=> feat: render event message on saleforce chat request fail

__tests__/app/actions.test.ts, __tests__/lib/handoff/SalesforceStrategy.test.ts, __tests__/packages/components/chat/EscalationFormDisplay.test.tsx, app/actions.ts, app/api/salesforce/utils.ts, app/constants/handoff.ts, index.ts, lib/handoff/HandoffStrategy.ts, lib/handoff/SalesforceStrategy.ts, lib/handoff/ZendeskStrategy.ts, messages/en.json, messages/es.json, messages/fr.json, messages/it.json, packages/components/ReactMarkdown.tsx, packages/components/chat/EscalationFormDisplay.tsx, settings.d.ts, types/salesforce/index.ts
Adds availability checking for handoff functionality. When enabled, checks agent availability before displaying the handoff button.
- Adds `isHandoffAvailable` server action to check Salesforce agent availability
- Adds availability check configuration options to handoff settings
- Updates EscalationFormDisplay to conditionally check availability before showing form
- Adds fallback message translations for when agents are unavailable
- Extracts Salesforce API version to constant
Loading state:
No POST request sent
=> Soln 94 create online rules for agent only allow live agent handoff

app/demo/[organizationId]/[agentId]/Widget.tsx, packages/widget/src/chat/components/ChatButton.tsx, packages/widget/src/chat/index.tsx
- Added `buttonLabel` property to widget configuration to allow customization of the chat button text
- Default value remains "Get Help" for backwards compatibility
- Propagated the button label property through the widget component
- Added `buttonLabel` to `WidgetLoadPayload` type in Widget.tsx
- Extended `ChatButtonProps` interface to include `buttonLabel` property
- Modified `load()` function to accept optional `buttonLabel` parameter
- Updated chat button component to render custom label instead of hardcoded text
- Existing functionality remains unchanged when no button label is provided
- Custom labels are properly displayed when specified in widget configuration
No breaking changes - existing implementations will continue to show "Get Help" by default
=> feat: add property for custom widget button label

__tests__/app/api/salesforce/messages/route.test.ts, app/api/salesforce/messages/route.ts
- Added keepalive mechanism to maintain Salesforce chat connection
- Sends minimal SSE keepalive message every 10 seconds
- Resets keepalive timer after sending chat messages
- Cleans up interval on stream close
- Added test suite for keepalive functionality
- Tests keepalive messages on idle connection
- Tests timer reset on message receipt
- Tests cleanup on stream end
=> feature: introduce handoff message stream keepalive

lib/handoff/FrontStrategy.ts
```json
{
"message": {
"type": "auto_reply",
...
},
"channel": "front:monarch:rodan:vF8l1vg8uxD3ZhpAgaYsB:message"
}
```
=> APP-245: fix typo in event.type

packages/components/chat/BailoutFormDisplay.tsx
Seeing some errors related to emails failing validation due to extra spaces
`Email address ckubacak@granger.txed.net  is invalid`
https://us3.datadoghq.com/logs?query=source%3Avercel%20-status%3A%28warn%20OR%20notice%20OR%20info%20OR%20ok%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZTSPLKw76la2wAAABhBWlRTUE1lQ0FBQTVFbFpMR0xfY2dnQUUAAAAkMDE5NGQyNDgtYzYzZi00YjU1LWI4NGUtNGFjODFhNDI4NDA0AAYhKQ&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=17295&storage=hot&stream_sort=desc&viz=stream&from_ts=1738681770454&to_ts=1738696170454&live=true
=> fix: trim all string form inputs

__tests__/app/actions.test.ts, __tests__/lib/settings.test.ts, __tests__/middleware.test.ts, app/actions.ts, app/api/server/utils.ts, lib/settings.ts, middleware.ts, settings.d.ts
- Fixed typo in settings adapter property name from `embedAllowList` to `embedAllowlist`
- Maintains backward compatibility with existing settings
- Ensures consistent property naming throughout the codebase
=> fix: correct typo in settings adapter

__tests__/app/[organizationId]/[agentId]/page.test.tsx, __tests__/lib/useIframeMessaging.test.ts, app/[organizationId]/[agentId]/page.tsx, lib/useIframeMessaging.ts
Adds the ability to disable automatic redirection to the demo page using a URL search parameter. This enhancement provides more flexibility in how the chat interface behaves when not in an iframe context.
- Added `disableRedirect` parameter to `useIframeMessaging` hook
- Updated redirection logic to respect the `disableRedirect` parameter
=> feat: add disable-redirect search param to demo

__tests__/app/api/zendesk/webhook/route.test.ts, app/api/zendesk/webhook/route.ts
- Added event filtering to skip delivery channel events
- Moved API logging check into request handler
- Renamed erroneous test file
- Added `BLOCKLIST_EVENTS` constant for filtered event types
- Events matching blocklist are skipped before Redis processing
=> feat: update zendesk webhook with event filter

packages/widget/src/main.tsx
- Chat widget extends `window.Maven` on load
- Preserves any existing Maven submodules, (e.g. instant answers)
=> fix(widget): safely extend Maven global object

__tests__/app/[organizationId]/[agentId]/page.test.tsx, __tests__/app/actions.test.ts, __tests__/i18n.test.ts, __tests__/lib/useIdleMessage.test.ts, app/[organizationId]/[agentId]/page.tsx, app/actions.ts, app/constants/internationalization.ts, i18n.ts, lib/settings.ts, lib/useIdleMessage.ts, messages/de.json, messages/en.json, messages/es.json, messages/fr.json, messages/it.json, messages/pt.json, middleware.ts, packages/components/chat/Chat.tsx, packages/widget/src/chat/hooks/useIframeCommunication.ts, packages/widget/src/chat/index.tsx, settings.d.ts
- Add idle timeout setting 
- Call useIdleTimeout on Chat Page Component (disabled if setting is not provided)
- Add manual locale override: widget -> url -> header -> i18n provider
- Add Portuguese and German locale support
- Improve settings type safety with spread operators
- Add tests for idle message and settings parsing
=> feat: add manual locale and idle message support

app/preview/[organizationId]/[agentId]/Widget.tsx, app/preview/[organizationId]/[agentId]/page.tsx
Adding `?customData={"locale":"fr"}` will get you:
=> feat: add locale search param option on preview page

__tests__/app/actions.test.ts, __tests__/lib/handoff/HandoffStrategyFactory.test.ts, __tests__/lib/handoff/SalesforceStrategy.test.ts, __tests__/lib/handoff/test-utils.ts, __tests__/lib/useHandoff.test.ts, app/actions.ts, lib/handoff/FrontStrategy.ts, lib/handoff/HandoffStrategyFactory.ts, lib/handoff/SalesforceStrategy.ts, lib/handoff/ZendeskStrategy.ts, lib/useHandoff.ts, settings.d.ts
Adds configuration option to end Salesforce handoffs based on specific message text.
- Added `handoffTerminatingMessageText` to `SalesforceHandoffConfiguration`
- Updated `SalesforceStrategy` to check message text against terminating text
- Added configuration passing through `HandoffStrategyFactory`
- Exposed `handoffTerminatingMessageText` in client-safe configuration
- Added tests for `SalesforceStrategy` terminating message behavior
- Added tests for configuration passing in `HandoffStrategyFactory`
- Added tests for client-safe configuration in `actions.test.ts`
- Added tests for configuration in `useHandoff`
=> feat: Add handoff terminating message configuration for Salesforce strategy

__tests__/app/actions.test.ts, __tests__/lib/settings.test.ts, __tests__/packages/components/chat/ChatHeader.test.tsx, __tests__/setup.ts, app/[organizationId]/[agentId]/page.tsx, lib/settings.ts, packages/components/chat/ChatHeader.tsx, settings.d.ts
Adds new `logo` field to `AppSettings` and deprecates `logoUrl`.
- Added `logo` field to `AppSettings.branding`
- Marked `logoUrl` as deprecated in both `LegacyAppSettings` and `AppSettings.branding`
- Updated `adaptLegacySettings` to handle logo migration
- Updated components to use new `logo` field
- Updated tests to verify logo field migration
- Added test cases for logo field migration paths
- Updated existing tests to use new field name
=> feat: add a new property to AppSettings for new logo field

app/api/front/conversations/route.ts
Context
- Vercel has a default 15 second function duration
- Front is tight w/ their rate-limits (rate limits are shared by company)
It doesn't happen often but here is an example where vercel needed to wait just a little longer
> START RequestId: 24ce07c6-a076-48b8-a149-307673b7bf81 [POST] /api/front/conversations status=504
> FRONT:: API Request failed { attempt: 0, message: 'Failed to fetch GET(429) /channels {"_error":{"status":429,"title":"Too Many Requests","message":"Rate limit exceeded. Please retry in 27510 milliseconds."}}', response: '', status: 429, statusText: 'Too Many Requests' }
Extending the function duration to have more time when front rate-limits are hit.
=> APP-1075: extend max duration for front handoff function

__tests__/lib/settings.test.ts, __tests__/packages/components/chat/ChatHeader.test.tsx, app/[organizationId]/[agentId]/page.tsx, lib/settings.ts, packages/components/chat/ChatHeader.tsx, settings.d.ts
This PR implements a fallback mechanism for the chat header logo to handle cases where image URLs might be invalid or inaccessible.
- Enhanced `ChatHeader` component with a three-layer fallback system:
1. Primary logo (`logo` prop)
2. Fallback logo (`fallbackLogo` prop from legacy fields)
3. Default logo (hardcoded)
- Added error handling to detect and recover from image loading failures
- Updated settings adapter to provide fallback logo URL from legacy settings
- Added type definition for `fallbackLogoUrl` in settings interface
- Updated page component to pass fallback logo to header
- Added test coverage for the fallback mechanism
- Used array-based approach for managing fallback sources
- Implemented memoization to prevent unnecessary recalculations
- Added proper error handling for …
=> feat: add fallback image to chat header

INSTALL.md, __tests__/packages/components/chat/Chat.test.tsx, packages/components/chat/Chat.tsx
Default brand font color has been changed to black in the `Chat` component. Documentation has been updated to reflect this change.
=> feat: change default brand font color to black

INSTALL.md
[APP-1088](https://linear.app/mavenagi/issue/APP-1088/defaults-results-in-bad-setup-for-chat-v2)
We now have set the `brandFontColor` to white for any agent installs that had just the `brandColor` set.
=> feat: update default colors

__tests__/packages/components/chat/WelcomeMessage.test.tsx, src/packages/components/chat/WelcomeChatMessage.tsx
Enhanced the `WelcomeMessage` component to support localized popular questions by:
- Adding support for popular questions as JSON translation objects
- Implementing locale-based question selection with English fallback
- Filtering out empty questions from the display
- Maintaining backward compatibility with string-based questions
The component now processes each question to check if it's a JSON translation object. If so, it extracts the appropriate translation based on the current locale. This allows for a more flexible approach to question localization without requiring changes to the component's API.
Added tests covering:
- Rendering localized questions from JSON objects
- Fallback to English when current locale is not available
- Filtering of empty questions
- Error handling for …
=> feat: accept translation object as popular question

__tests__/lib/handoff/HandoffStrategyFactory.test.ts, __tests__/lib/handoff/SalesforceMessagingStrategy.test.ts, settings.d.ts, src/lib/handoff/HandoffStrategyFactory.ts, src/lib/handoff/SalesforceMessagingStrategy.ts, src/lib/handoff/ServerHandoffStrategyFactory.ts
Adds support for Salesforce Messaging as a handoff strategy.
- Add `SalesforceMessagingStrategy` class implementing `HandoffStrategy` interface
- Add `SalesforceServerStrategy` class implementing `ServerHandoffStrategy` interface
- Update `HandoffStrategyFactory` to support "salesforce-messaging" type
- Add tests for new strategy and factory updates
- Update type definitions for Salesforce Messaging configuration
=> feat: add salesforce-messaging strategy

__tests__/app/api/zendesk/conversations/route.test.ts, settings.d.ts, src/app/api/zendesk/conversations/route.ts
Adds a temporary workaround to display custom fields in Zendesk handoff conversations. This will be removed once the root issue is resolved.
Changes:
- Add shouldIncludeCustomFieldsInHandoffMessage config option
- Add createCustomFieldsMesage helper function
The custom fields message will be displayed in the ZD conversation when shouldIncludeCustomFieldsInHandoffMessage is enabled, allowing agents to see custom field values during handoff.
=> feat: zendesk live handoff include custom fields message
